### ISSUE TITLE
test_no_underscores_all_dashes doesn't like git urls with underscores

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/requirements-tools#24]
```
E   AssertionError: Use dashes for package names requirements.txt: -e git+https://github.com/EvanKrall/a_sync@cc2bc2799db9104eca9ca535884492b6114757cb#egg=a-sync
```

Seems like it should only care about the egg name.

**Comment by asottile** [comment]
`requirements-tools` explicitly forbids git urls, so this is working as intended

**Comment by EvanKrall** [comment]
![image](https://user-images.githubusercontent.com/233961/40257791-5b9435c4-5aa4-11e8-847d-f281bcb01177.png)

So uh, how am I supposed to run a forked version of a library?

**Comment by asottile** [comment]
At least at yelp, you're supposed to promote a `.post1` version of a library internally.  Talk to @chriskuehl and he can help you set this up :)

**Comment by EvanKrall** [comment]
That works great for internal builds. What about [open source projects](https://github.com/Yelp/paasta/) which don't always build on a box where our internal pypi server is available? I could, but don't want to, set up a publicly-available pypi server just to publish a version of a library until a PR gets merged.

**Comment by asottile** [comment]
requirements-tools is intended to be an intentionally strict toolset to enforce best practices for deploying an application.  some of these best practices include:
- only using built packages (`check-all-wheels` is helpful for this)
- only installing from things where dependencies can be verified  (vcs / https / easy_install / editable / etc. are all categories of things for which this cannot be validated)

Since vcs urls don't work for either of these requirements, they are strictly forbidden (plus you really shouldn't ship a version control system with your application).

It also intentionally prevents running unreleased forks (such as running from a random feature branch from git) -- I understand this is exactly what you're trying to do, but this is exactly what `requirements-tools` is trying to prevent.
